server:
  port: 9002

spring:
  application:
    name: COURSE-SERVICE
  datasource:
    url: jdbc:mysql:///hrm-course?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
hrm:
  swagger:
    title: 课程管理服务
    description: 课程管理服务的接口文档